# Generated by Django 4.2.6 on 2023-10-19 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gvit_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='hire_date',
        ),
    ]
